catch { create_links -hdl_source "$here/corefft_stream64_adapter.v" }
build_design_hierarchy
catch { create_hdl_core -file "$here/corefft_stream64_adapter.v" -module {corefft_stream64_adapter} -library {work} }
catch { create_links -hdl_source "$here/sar_axi_idconv.v" }
build_design_hierarchy
catch { create_hdl_core -file "$here/sar_axi_idconv.v" -module {sar_axi_idconv} -library {work} }
catch { hdl_core_add_bif -hdl_core_name {sar_axi_idconv} -bif_definition {AXI4:AMBA:AMBA4:slave} -bif_name {S_AXI} -signal_map {} }
catch { hdl_core_assign_bif_signal -hdl_core_name {sar_axi_idconv} -bif_name {S_AXI} -bif_signal_name {ARADDR} -core_signal_name {S_AXI_ARADDR} }
catch { hdl_core_assign_bif_signal -hdl_core_name {sar_axi_idconv} -bif_name {S_AXI} -bif_signal_name {ARBURST} -core_signal_name {S_AXI_ARBURST} }
catch { hdl_core_assign_bif_signal -hdl_core_name {sar_axi_idconv} -bif_name {S_AXI} -bif_signal_name {ARCACHE} -core_signal_name {S_AXI_ARCACHE} }
catch { hdl_core_assign_bif_signal -hdl_core_name {sar_axi_idconv} -bif_name {S_AXI} -bif_signal_name {ARID} -core_signal_name {S_AXI_ARID} }
catch { hdl_core_assign_bif_signal -hdl_core_name {sar_axi_idconv} -bif_name {S_AXI} -bif_signal_name {ARLEN} -core_signal_name {S_AXI_ARLEN} }
catch { hdl_core_assign_bif_signal -hdl_core_name {sar_axi_idconv} -bif_name {S_AXI} -bif_signal_name {ARLOCK} -core_signal_name {S_AXI_ARLOCK} }
catch { hdl_core_assign_bif_signal -hdl_core_name {sar_axi_idconv} -bif_name {S_AXI} -bif_signal_name {ARPROT} -core_signal_name {S_AXI_ARPROT} }
catch { hdl_core_assign_bif_signal -hdl_core_name {sar_axi_idconv} -bif_name {S_AXI} -bif_signal_name {ARQOS} -core_signal_name {S_AXI_ARQOS} }
catch { hdl_core_assign_bif_signal -hdl_core_name {sar_axi_idconv} -bif_name {S_AXI} -bif_signal_name {ARREADY} -core_signal_name {S_AXI_ARREADY} }
catch { hdl_core_assign_bif_signal -hdl_core_name {sar_axi_idconv} -bif_name {S_AXI} -bif_signal_name {ARREGION} -core_signal_name {S_AXI_ARREGION} }
catch { hdl_core_assign_bif_signal -hdl_core_name {sar_axi_idconv} -bif_name {S_AXI} -bif_signal_name {ARSIZE} -core_signal_name {S_AXI_ARSIZE} }
catch { hdl_core_assign_bif_signal -hdl_core_name {sar_axi_idconv} -bif_name {S_AXI} -bif_signal_name {ARUSER} -core_signal_name {S_AXI_ARUSER} }
catch { hdl_core_assign_bif_signal -hdl_core_name {sar_axi_idconv} -bif_name {S_AXI} -bif_signal_name {ARVALID} -core_signal_name {S_AXI_ARVALID} }
catch { hdl_core_assign_bif_signal -hdl_core_name {sar_axi_idconv} -bif_name {S_AXI} -bif_signal_name {AWADDR} -core_signal_name {S_AXI_AWADDR} }
catch { hdl_core_assign_bif_signal -hdl_core_name {sar_axi_idconv} -bif_name {S_AXI} -bif_signal_name {AWBURST} -core_signal_name {S_AXI_AWBURST} }
catch { hdl_core_assign_bif_signal -hdl_core_name {sar_axi_idconv} -bif_name {S_AXI} -bif_signal_name {AWCACHE} -core_signal_name {S_AXI_AWCACHE} }
catch { hdl_core_assign_bif_signal -hdl_core_name {sar_axi_idconv} -bif_name {S_AXI} -bif_signal_name {AWID} -core_signal_name {S_AXI_AWID} }
catch { hdl_core_assign_bif_signal -hdl_core_name {sar_axi_idconv} -bif_name {S_AXI} -bif_signal_name {AWLEN} -core_signal_name {S_AXI_AWLEN} }
catch { hdl_core_assign_bif_signal -hdl_core_name {sar_axi_idconv} -bif_name {S_AXI} -bif_signal_name {AWLOCK} -core_signal_name {S_AXI_AWLOCK} }
catch { hdl_core_assign_bif_signal -hdl_core_name {sar_axi_idconv} -bif_name {S_AXI} -bif_signal_name {AWPROT} -core_signal_name {S_AXI_AWPROT} }
catch { hdl_core_assign_bif_signal -hdl_core_name {sar_axi_idconv} -bif_name {S_AXI} -bif_signal_name {AWQOS} -core_signal_name {S_AXI_AWQOS} }
catch { hdl_core_assign_bif_signal -hdl_core_name {sar_axi_idconv} -bif_name {S_AXI} -bif_signal_name {AWREADY} -core_signal_name {S_AXI_AWREADY} }
catch { hdl_core_assign_bif_signal -hdl_core_name {sar_axi_idconv} -bif_name {S_AXI} -bif_signal_name {AWREGION} -core_signal_name {S_AXI_AWREGION} }
catch { hdl_core_assign_bif_signal -hdl_core_name {sar_axi_idconv} -bif_name {S_AXI} -bif_signal_name {AWSIZE} -core_signal_name {S_AXI_AWSIZE} }
catch { hdl_core_assign_bif_signal -hdl_core_name {sar_axi_idconv} -bif_name {S_AXI} -bif_signal_name {AWUSER} -core_signal_name {S_AXI_AWUSER} }
catch { hdl_core_assign_bif_signal -hdl_core_name {sar_axi_idconv} -bif_name {S_AXI} -bif_signal_name {AWVALID} -core_signal_name {S_AXI_AWVALID} }
catch { hdl_core_assign_bif_signal -hdl_core_name {sar_axi_idconv} -bif_name {S_AXI} -bif_signal_name {BID} -core_signal_name {S_AXI_BID} }
catch { hdl_core_assign_bif_signal -hdl_core_name {sar_axi_idconv} -bif_name {S_AXI} -bif_signal_name {BREADY} -core_signal_name {S_AXI_BREADY} }
catch { hdl_core_assign_bif_signal -hdl_core_name {sar_axi_idconv} -bif_name {S_AXI} -bif_signal_name {BRESP} -core_signal_name {S_AXI_BRESP} }
catch { hdl_core_assign_bif_signal -hdl_core_name {sar_axi_idconv} -bif_name {S_AXI} -bif_signal_name {BVALID} -core_signal_name {S_AXI_BVALID} }
catch { hdl_core_assign_bif_signal -hdl_core_name {sar_axi_idconv} -bif_name {S_AXI} -bif_signal_name {RDATA} -core_signal_name {S_AXI_RDATA} }
catch { hdl_core_assign_bif_signal -hdl_core_name {sar_axi_idconv} -bif_name {S_AXI} -bif_signal_name {RID} -core_signal_name {S_AXI_RID} }
catch { hdl_core_assign_bif_signal -hdl_core_name {sar_axi_idconv} -bif_name {S_AXI} -bif_signal_name {RLAST} -core_signal_name {S_AXI_RLAST} }
catch { hdl_core_assign_bif_signal -hdl_core_name {sar_axi_idconv} -bif_name {S_AXI} -bif_signal_name {RREADY} -core_signal_name {S_AXI_RREADY} }
catch { hdl_core_assign_bif_signal -hdl_core_name {sar_axi_idconv} -bif_name {S_AXI} -bif_signal_name {RRESP} -core_signal_name {S_AXI_RRESP} }
catch { hdl_core_assign_bif_signal -hdl_core_name {sar_axi_idconv} -bif_name {S_AXI} -bif_signal_name {RVALID} -core_signal_name {S_AXI_RVALID} }
catch { hdl_core_assign_bif_signal -hdl_core_name {sar_axi_idconv} -bif_name {S_AXI} -bif_signal_name {WDATA} -core_signal_name {S_AXI_WDATA} }
catch { hdl_core_assign_bif_signal -hdl_core_name {sar_axi_idconv} -bif_name {S_AXI} -bif_signal_name {WLAST} -core_signal_name {S_AXI_WLAST} }
catch { hdl_core_assign_bif_signal -hdl_core_name {sar_axi_idconv} -bif_name {S_AXI} -bif_signal_name {WREADY} -core_signal_name {S_AXI_WREADY} }
catch { hdl_core_assign_bif_signal -hdl_core_name {sar_axi_idconv} -bif_name {S_AXI} -bif_signal_name {WSTRB} -core_signal_name {S_AXI_WSTRB} }
catch { hdl_core_assign_bif_signal -hdl_core_name {sar_axi_idconv} -bif_name {S_AXI} -bif_signal_name {WUSER} -core_signal_name {S_AXI_WUSER} }
catch { hdl_core_assign_bif_signal -hdl_core_name {sar_axi_idconv} -bif_name {S_AXI} -bif_signal_name {WVALID} -core_signal_name {S_AXI_WVALID} }
catch { hdl_core_add_bif -hdl_core_name {sar_axi_idconv} -bif_definition {AXI4:AMBA:AMBA4:master} -bif_name {M_AXI} -signal_map {} }
catch { hdl_core_assign_bif_signal -hdl_core_name {sar_axi_idconv} -bif_name {M_AXI} -bif_signal_name {ARADDR} -core_signal_name {M_AXI_ARADDR} }
catch { hdl_core_assign_bif_signal -hdl_core_name {sar_axi_idconv} -bif_name {M_AXI} -bif_signal_name {ARBURST} -core_signal_name {M_AXI_ARBURST} }
catch { hdl_core_assign_bif_signal -hdl_core_name {sar_axi_idconv} -bif_name {M_AXI} -bif_signal_name {ARCACHE} -core_signal_name {M_AXI_ARCACHE} }
catch { hdl_core_assign_bif_signal -hdl_core_name {sar_axi_idconv} -bif_name {M_AXI} -bif_signal_name {ARID} -core_signal_name {M_AXI_ARID} }
catch { hdl_core_assign_bif_signal -hdl_core_name {sar_axi_idconv} -bif_name {M_AXI} -bif_signal_name {ARLEN} -core_signal_name {M_AXI_ARLEN} }
catch { hdl_core_assign_bif_signal -hdl_core_name {sar_axi_idconv} -bif_name {M_AXI} -bif_signal_name {ARLOCK} -core_signal_name {M_AXI_ARLOCK} }
catch { hdl_core_assign_bif_signal -hdl_core_name {sar_axi_idconv} -bif_name {M_AXI} -bif_signal_name {ARPROT} -core_signal_name {M_AXI_ARPROT} }
catch { hdl_core_assign_bif_signal -hdl_core_name {sar_axi_idconv} -bif_name {M_AXI} -bif_signal_name {ARQOS} -core_signal_name {M_AXI_ARQOS} }
catch { hdl_core_assign_bif_signal -hdl_core_name {sar_axi_idconv} -bif_name {M_AXI} -bif_signal_name {ARREADY} -core_signal_name {M_AXI_ARREADY} }
catch { hdl_core_assign_bif_signal -hdl_core_name {sar_axi_idconv} -bif_name {M_AXI} -bif_signal_name {ARSIZE} -core_signal_name {M_AXI_ARSIZE} }
catch { hdl_core_assign_bif_signal -hdl_core_name {sar_axi_idconv} -bif_name {M_AXI} -bif_signal_name {ARVALID} -core_signal_name {M_AXI_ARVALID} }
catch { hdl_core_assign_bif_signal -hdl_core_name {sar_axi_idconv} -bif_name {M_AXI} -bif_signal_name {AWADDR} -core_signal_name {M_AXI_AWADDR} }
catch { hdl_core_assign_bif_signal -hdl_core_name {sar_axi_idconv} -bif_name {M_AXI} -bif_signal_name {AWBURST} -core_signal_name {M_AXI_AWBURST} }
catch { hdl_core_assign_bif_signal -hdl_core_name {sar_axi_idconv} -bif_name {M_AXI} -bif_signal_name {AWCACHE} -core_signal_name {M_AXI_AWCACHE} }
catch { hdl_core_assign_bif_signal -hdl_core_name {sar_axi_idconv} -bif_name {M_AXI} -bif_signal_name {AWID} -core_signal_name {M_AXI_AWID} }
catch { hdl_core_assign_bif_signal -hdl_core_name {sar_axi_idconv} -bif_name {M_AXI} -bif_signal_name {AWLEN} -core_signal_name {M_AXI_AWLEN} }
catch { hdl_core_assign_bif_signal -hdl_core_name {sar_axi_idconv} -bif_name {M_AXI} -bif_signal_name {AWLOCK} -core_signal_name {M_AXI_AWLOCK} }
catch { hdl_core_assign_bif_signal -hdl_core_name {sar_axi_idconv} -bif_name {M_AXI} -bif_signal_name {AWPROT} -core_signal_name {M_AXI_AWPROT} }
catch { hdl_core_assign_bif_signal -hdl_core_name {sar_axi_idconv} -bif_name {M_AXI} -bif_signal_name {AWQOS} -core_signal_name {M_AXI_AWQOS} }
catch { hdl_core_assign_bif_signal -hdl_core_name {sar_axi_idconv} -bif_name {M_AXI} -bif_signal_name {AWREADY} -core_signal_name {M_AXI_AWREADY} }
catch { hdl_core_assign_bif_signal -hdl_core_name {sar_axi_idconv} -bif_name {M_AXI} -bif_signal_name {AWSIZE} -core_signal_name {M_AXI_AWSIZE} }
catch { hdl_core_assign_bif_signal -hdl_core_name {sar_axi_idconv} -bif_name {M_AXI} -bif_signal_name {AWVALID} -core_signal_name {M_AXI_AWVALID} }
catch { hdl_core_assign_bif_signal -hdl_core_name {sar_axi_idconv} -bif_name {M_AXI} -bif_signal_name {BID} -core_signal_name {M_AXI_BID} }
catch { hdl_core_assign_bif_signal -hdl_core_name {sar_axi_idconv} -bif_name {M_AXI} -bif_signal_name {BREADY} -core_signal_name {M_AXI_BREADY} }
catch { hdl_core_assign_bif_signal -hdl_core_name {sar_axi_idconv} -bif_name {M_AXI} -bif_signal_name {BRESP} -core_signal_name {M_AXI_BRESP} }
catch { hdl_core_assign_bif_signal -hdl_core_name {sar_axi_idconv} -bif_name {M_AXI} -bif_signal_name {BVALID} -core_signal_name {M_AXI_BVALID} }
catch { hdl_core_assign_bif_signal -hdl_core_name {sar_axi_idconv} -bif_name {M_AXI} -bif_signal_name {RDATA} -core_signal_name {M_AXI_RDATA} }
catch { hdl_core_assign_bif_signal -hdl_core_name {sar_axi_idconv} -bif_name {M_AXI} -bif_signal_name {RID} -core_signal_name {M_AXI_RID} }
catch { hdl_core_assign_bif_signal -hdl_core_name {sar_axi_idconv} -bif_name {M_AXI} -bif_signal_name {RLAST} -core_signal_name {M_AXI_RLAST} }
catch { hdl_core_assign_bif_signal -hdl_core_name {sar_axi_idconv} -bif_name {M_AXI} -bif_signal_name {RREADY} -core_signal_name {M_AXI_RREADY} }
catch { hdl_core_assign_bif_signal -hdl_core_name {sar_axi_idconv} -bif_name {M_AXI} -bif_signal_name {RRESP} -core_signal_name {M_AXI_RRESP} }
catch { hdl_core_assign_bif_signal -hdl_core_name {sar_axi_idconv} -bif_name {M_AXI} -bif_signal_name {RVALID} -core_signal_name {M_AXI_RVALID} }
catch { hdl_core_assign_bif_signal -hdl_core_name {sar_axi_idconv} -bif_name {M_AXI} -bif_signal_name {WDATA} -core_signal_name {M_AXI_WDATA} }
catch { hdl_core_assign_bif_signal -hdl_core_name {sar_axi_idconv} -bif_name {M_AXI} -bif_signal_name {WLAST} -core_signal_name {M_AXI_WLAST} }
catch { hdl_core_assign_bif_signal -hdl_core_name {sar_axi_idconv} -bif_name {M_AXI} -bif_signal_name {WREADY} -core_signal_name {M_AXI_WREADY} }
catch { hdl_core_assign_bif_signal -hdl_core_name {sar_axi_idconv} -bif_name {M_AXI} -bif_signal_name {WSTRB} -core_signal_name {M_AXI_WSTRB} }
catch { hdl_core_assign_bif_signal -hdl_core_name {sar_axi_idconv} -bif_name {M_AXI} -bif_signal_name {WVALID} -core_signal_name {M_AXI_WVALID} }
build_design_hierarchy
