// auto-generated by gen_vectors.py -- do not edit
`define VEC_M   10
`define VEC_N   6
`define VEC_M2  16
`define VEC_N2  8
`define VEC_SIG_ADDR 64'h0000000000001000
`define VEC_BUF_ADDR 64'h0000000000003000
`define VEC_OUT_ADDR 64'h0000000000005000
`define VEC_EXP_R 1
`define VEC_EXP_A 3
`define VEC_MAG_TOL 3
`define VEC_SIG_HEX "sig.hex"
`define VEC_GOLDEN_HEX "golden.hex"
