// tb_sar_fft_top.sv -- self-checking top testbench for the SAR FFT accelerator.
//
// Loads the input k-space (sig.hex) into a behavioral DDR, programs the control
// registers over AXI4-Lite, launches the core, waits for DONE, then compares the
// output magnitude image in DDR against golden.hex (generated by the same model
// the RTL implements; see fpga/scripts/gen_vectors.py). Tolerance-based, because
// the behavioral CoreFFT's real-arithmetic DFT differs from numpy by a few ULP.
//
// Run from fpga/sim/vectors/ (where the .hex files live). See run_modelsim.do.
`timescale 1ns/1ps
`default_nettype none
`include "params.vh"

module tb_sar_fft_top;
    localparam int N2  = `VEC_N2;
    localparam int M2  = `VEC_M2;
    localparam int LOG2_R = $clog2(N2);
    localparam int LOG2_A = $clog2(M2);
    localparam int NPIX = M2 * N2;

    logic clk = 0, rstn = 0;
    always #5 clk = ~clk;             // 100 MHz

    // ---- AXI4-Lite driver signals ----
    logic [7:0]  awaddr;  logic awvalid;  wire awready;
    logic [31:0] wdata;   logic [3:0] wstrb; logic wvalid; wire wready;
    wire  [1:0]  bresp;   wire bvalid;     logic bready;
    logic [7:0]  araddr;  logic arvalid;   wire arready;
    wire  [31:0] rdata;   wire [1:0] rresp; wire rvalid;  logic rready;

    // ---- AXI4 master <-> DDR ----
    wire [3:0]  awid_m;  wire [63:0] awaddr_m; wire [7:0] awlen_m; wire [2:0] awsize_m;
    wire [1:0]  awburst_m; wire awvalid_m, awready_m;
    wire [31:0] wdata_m; wire [3:0] wstrb_m; wire wlast_m, wvalid_m, wready_m;
    wire [3:0]  bid_m;   wire [1:0] bresp_m; wire bvalid_m, bready_m;
    wire [3:0]  arid_m;  wire [63:0] araddr_m; wire [7:0] arlen_m; wire [2:0] arsize_m;
    wire [1:0]  arburst_m; wire arvalid_m, arready_m;
    wire [3:0]  rid_m;   wire [31:0] rdata_m; wire [1:0] rresp_m; wire rlast_m, rvalid_m, rready_m;
    wire        irq;

    sar_fft_top #(
        .FFT_LEN_R(N2), .LOG2_R(LOG2_R), .FFT_LEN_A(M2), .LOG2_A(LOG2_A),
        .ADDR_W(64), .AXI_ID_W(4)
    ) dut (
        .clk(clk), .rstn(rstn), .irq(irq),
        .s_axil_awaddr(awaddr), .s_axil_awvalid(awvalid), .s_axil_awready(awready),
        .s_axil_wdata(wdata), .s_axil_wstrb(wstrb), .s_axil_wvalid(wvalid), .s_axil_wready(wready),
        .s_axil_bresp(bresp), .s_axil_bvalid(bvalid), .s_axil_bready(bready),
        .s_axil_araddr(araddr), .s_axil_arvalid(arvalid), .s_axil_arready(arready),
        .s_axil_rdata(rdata), .s_axil_rresp(rresp), .s_axil_rvalid(rvalid), .s_axil_rready(rready),
        .m_axi_awid(awid_m), .m_axi_awaddr(awaddr_m), .m_axi_awlen(awlen_m), .m_axi_awsize(awsize_m),
        .m_axi_awburst(awburst_m), .m_axi_awvalid(awvalid_m), .m_axi_awready(awready_m),
        .m_axi_wdata(wdata_m), .m_axi_wstrb(wstrb_m), .m_axi_wlast(wlast_m),
        .m_axi_wvalid(wvalid_m), .m_axi_wready(wready_m),
        .m_axi_bid(bid_m), .m_axi_bresp(bresp_m), .m_axi_bvalid(bvalid_m), .m_axi_bready(bready_m),
        .m_axi_arid(arid_m), .m_axi_araddr(araddr_m), .m_axi_arlen(arlen_m), .m_axi_arsize(arsize_m),
        .m_axi_arburst(arburst_m), .m_axi_arvalid(arvalid_m), .m_axi_arready(arready_m),
        .m_axi_rid(rid_m), .m_axi_rdata(rdata_m), .m_axi_rresp(rresp_m), .m_axi_rlast(rlast_m),
        .m_axi_rvalid(rvalid_m), .m_axi_rready(rready_m)
    );

    axi_ddr_model #(.ADDR_W(64), .ID_W(4), .MEM_WORDS(1<<14), .LAT(3)) u_ddr (
        .clk(clk), .rstn(rstn),
        .awid(awid_m), .awaddr(awaddr_m), .awlen(awlen_m), .awsize(awsize_m),
        .awburst(awburst_m), .awvalid(awvalid_m), .awready(awready_m),
        .wdata(wdata_m), .wstrb(wstrb_m), .wlast(wlast_m), .wvalid(wvalid_m), .wready(wready_m),
        .bid(bid_m), .bresp(bresp_m), .bvalid(bvalid_m), .bready(bready_m),
        .arid(arid_m), .araddr(araddr_m), .arlen(arlen_m), .arsize(arsize_m),
        .arburst(arburst_m), .arvalid(arvalid_m), .arready(arready_m),
        .rid(rid_m), .rdata(rdata_m), .rresp(rresp_m), .rlast(rlast_m),
        .rvalid(rvalid_m), .rready(rready_m)
    );

    // ---------------- AXI4-Lite BFM tasks ----------------
    task automatic axil_write(input [7:0] a, input [31:0] d);
        begin
            @(posedge clk);
            awaddr <= a; awvalid <= 1; wdata <= d; wstrb <= 4'hf; wvalid <= 1; bready <= 1;
            wait (awready); wait (wready);
            @(posedge clk); awvalid <= 0; wvalid <= 0;
            wait (bvalid);
            @(posedge clk); bready <= 0;
        end
    endtask

    task automatic axil_read(input [7:0] a, output [31:0] d);
        begin
            @(posedge clk);
            araddr <= a; arvalid <= 1; rready <= 1;
            wait (arready);
            @(posedge clk); arvalid <= 0;
            wait (rvalid); d = rdata;
            @(posedge clk); rready <= 0;
        end
    endtask

    // ---------------- test sequence ----------------
    reg [31:0] gold [0:NPIX-1];
    integer k, errors, dmax;
    integer got, exp_v, diff;
    reg [31:0] st, rd_exp_r, rd_exp_a, rd_id;
    integer sig_word, out_word;
    integer timeout;

    initial begin
        awvalid=0; wvalid=0; bready=0; arvalid=0; rready=0; awaddr=0; araddr=0; wdata=0; wstrb=0;
        // preload input k-space into DDR and golden into a TB array
        sig_word = `VEC_SIG_ADDR >> 2;
        out_word = `VEC_OUT_ADDR >> 2;
        $readmemh(`VEC_SIG_HEX, u_ddr.mem, sig_word);
        $readmemh(`VEC_GOLDEN_HEX, gold);

        repeat (5) @(posedge clk);
        rstn <= 1;
        repeat (5) @(posedge clk);

        // sanity: design id
        axil_read(8'h3C, rd_id);
        if (rd_id !== 32'h5341_5246) $display("WARN: ID mismatch 0x%08x", rd_id);

        // program dimensions + buffer addresses
        axil_write(8'h0C, `VEC_M);
        axil_write(8'h10, `VEC_N);
        axil_write(8'h14, M2);
        axil_write(8'h18, N2);
        axil_write(8'h1C, `VEC_SIG_ADDR & 64'hFFFF_FFFF);
        axil_write(8'h20, `VEC_SIG_ADDR >> 32);
        axil_write(8'h24, `VEC_BUF_ADDR & 64'hFFFF_FFFF);
        axil_write(8'h28, `VEC_BUF_ADDR >> 32);
        axil_write(8'h2C, `VEC_OUT_ADDR & 64'hFFFF_FFFF);
        axil_write(8'h30, `VEC_OUT_ADDR >> 32);

        // launch
        axil_write(8'h00, 32'h1);   // CTRL.START

        // wait for DONE (poll STATUS.DONE), with timeout
        st = 0; timeout = 0;
        while (!st[0]) begin
            axil_read(8'h04, st);
            timeout = timeout + 1;
            if (timeout > 200000) begin
                $display("FAIL: timeout waiting for DONE");
                $finish;
            end
        end
        if (st[2]) begin $display("FAIL: STATUS.ERR set (dim/FFT-length mismatch?)"); $finish; end

        axil_read(8'h34, rd_exp_r);
        axil_read(8'h38, rd_exp_a);
        $display("EXP_R=%0d (golden %0d)   EXP_A=%0d (golden %0d)",
                 rd_exp_r, `VEC_EXP_R, rd_exp_a, `VEC_EXP_A);

        // compare output magnitude image
        errors = 0; dmax = 0;
        for (k = 0; k < NPIX; k = k + 1) begin
            got = u_ddr.mem[out_word + k];
            exp_v = gold[k];
            diff = (got > exp_v) ? (got - exp_v) : (exp_v - got);
            if (diff > dmax) dmax = diff;
            if (diff > `VEC_MAG_TOL) begin
                errors = errors + 1;
                if (errors <= 10)
                    $display("  pix %0d (r%0d,c%0d): got %0d exp %0d (diff %0d)",
                             k, k/N2, k%N2, got, exp_v, diff);
            end
        end

        $display("--------------------------------------------------");
        $display("checked %0d pixels, max abs diff = %0d, tol = %0d, mismatches = %0d",
                 NPIX, dmax, `VEC_MAG_TOL, errors);
        if (errors == 0) $display("RESULT: PASS");
        else             $display("RESULT: FAIL (%0d mismatches)", errors);
        $display("--------------------------------------------------");
        $finish;
    end

    // global watchdog
    initial begin
        #50_000_000;
        $display("FAIL: global watchdog timeout");
        $finish;
    end
endmodule
`default_nettype wire
