#!/usr/bin/env python3
# gen_twiddle.py -- emit twiddle.h for hls::dsp::fft_in_place<SIZE> (SmartHLS DSP lib).
#
# The shipped external/dsp/include/twiddle.h is sized for a 256-point FFT. This
# generator emits the byte-identical format for an arbitrary power-of-two SIZE
# (default 8192) so the kernel can #include a local twiddle.h in place of the
# library's.
#
# Format matched exactly from the shipped 256-pt file:
#   #pragma HLS memory partition variable(twiddleRe) type(block) factor(8)
#   static const hls::ap_fixpt<16, 1> twiddleRe[ ] = {
#       ap_fixpt<16, 1>("7FFF"),   //     0 32767 = 1.0
#       ...
#   };
#   (then the same for twiddleIm)
#
# Each array has SIZE/2 entries indexed by k = 0 .. SIZE/2-1:
#   twiddleRe[k] =  cos(2*pi*k/SIZE)
#   twiddleIm[k] = -sin(2*pi*k/SIZE)
# Value encoding: ap_fixpt<16,1> is Q1.15. The hex literal is the raw 16-bit
# two's-complement pattern of round(value * 32767) (0x7FFF == +1.0). This
# reproduces the shipped table's rounding (e.g. k=1 Re -> 0x7FF5 = 32757).
import math

SIZE = 8192
HALF = SIZE // 2
SCALE = 32767  # 0x7FFF represents +1.0 in the shipped table

def q15_hex(v):
    # clamp to signed 16-bit range after scaling+rounding
    r = int(round(v * SCALE))
    if r > 32767:
        r = 32767
    if r < -32768:
        r = -32768
    return r & 0xFFFF, r

def emit_array(name, func):
    lines = []
    lines.append('#pragma HLS memory partition variable(%s) type(block) factor(8)' % name)
    lines.append('// array size is FFT_SIZE / 2')
    lines.append('static const hls::ap_fixpt<16, 1> %s[ ] = {' % name)
    for k in range(HALF):
        v = func(k)
        raw, signed = q15_hex(v)
        comment = '// %d = %s' % (signed, repr(v))
        term = ',' if k != HALF - 1 else ''
        lines.append('    ap_fixpt<16, 1>("%04X")%s   %s' % (raw, term, comment))
    lines.append('};')
    return '\n'.join(lines)

re_func = lambda k: math.cos(2.0 * math.pi * k / SIZE)
im_func = lambda k: -math.sin(2.0 * math.pi * k / SIZE)

out = []
out.append('// twiddle.h -- AUTO-GENERATED by gen_twiddle.py for SIZE=%d (do not hand-edit).' % SIZE)
out.append('// twiddleRe[k]=cos(2*pi*k/SIZE), twiddleIm[k]=-sin(2*pi*k/SIZE), Q1.15 (0x7FFF=+1.0).')
out.append(emit_array('twiddleRe', re_func))
out.append('')
out.append(emit_array('twiddleIm', im_func))
out.append('')

with open('twiddle.h', 'w') as f:
    f.write('\n'.join(out))
print('wrote twiddle.h: SIZE=%d, %d entries per array' % (SIZE, HALF))
